---
title: "Assignment 3"
author: "Annie Beyer and Caleb Aguiar"
date: "1/25/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1


```{r}
tide128_rev<-sum(detergent_DF$q_tide128*detergent_DF$p_tide128)
tide64_rev<-sum(detergent_DF$q_tide64*detergent_DF$p_tide64)
wisk64_rev<-sum(detergent_DF$q_wisk64*detergent_DF$p_wisk64)

tide128_per<-tide128_rev/(tide64_rev+wisk64_rev+tide128_rev)
tide64_per<-tide64_rev/(tide128_rev+wisk64_rev+tide64_rev)
wisk64_per<-wisk64_rev/(tide64_rev+tide128_rev+wisk64_rev)

total<-tide128_per+tide64_per+wisk64_per

library(psych)

describe(detergent_DF)

Product<-c("Tide 128","Tide 64","Wisk 64")
Revenue<-c(tide128_rev,tide64_rev,wisk64_rev)
Marketshare_Percent<-c(tide128_per,tide64_per,wisk64_per)

Marketshare_table<-data.frame(Product,Revenue,Marketshare_Percent)

Marketshare_table

```



Perform the analysis for Q1 and the fill out this Table.

: Table of marketshare (in percentage) and price statistics (in dollars)

+---------------+---------------+-------------+--------------+-----------+
| Product       | Marketshare   | Mean Price  | Median Price | Std. Dev |          
+===============+===============+=============+==============+===========+
| Tide 128 oz   |     .569      |   8.36      |    8.48      |  .76      |
+---------------+---------------+-------------+--------------+-----------+
| Tide 64 oz    |     .263      |   4.36      |    4.42      |  .40      |
+---------------+---------------+-------------+--------------+-----------+
| Wisk 64 oz    |     .168      |   4.07      |    4.19      |  .49      |
+---------------+---------------+-------------+--------------+-----------+


## Question 6

: Table of quantities sold and profits when Tide changes the price of Tide 64 and 128. Price changes are shown in percentages

+---------------+---------------+-------------+--------------+---------------+
| del_price_128 | del_price_64  | q_128       | q_64         | Total profits |          
+===============+===============+=============+==============+===============+
| 0.05          | 0.05          |             |              |               |
+---------------+---------------+-------------+--------------+---------------+
| -0.05         | -0.05         |             |              |               |
+---------------+---------------+-------------+--------------+---------------+
| 0.05          | -0.05         |             |              |               |
+---------------+---------------+-------------+--------------+---------------+
| -0.05         | 0.05          |             |              |               |
+---------------+---------------+-------------+--------------+---------------+
